### ISSUE TITLE
App crashes on second login attempt

### ISSUE THREAD

**Issue by Ghoral** [evilrat/flutter_zoom_sdk#33] opened 2021-12-12 10:36 UTC
After login error. If you try to login again then app crashes.

**Comment by evilrat** [comment] 2021-12-13 05:06
Send log here...please

**Comment by Ghoral** [comment] 2021-12-13 08:07
@evilrat here is the log

D/Zoom Flutter(18719): [onLoginError] : 3
E/AndroidRuntime(18719): FATAL EXCEPTION: main
E/AndroidRuntime(18719): Process: applicationname, PID: 18719
E/AndroidRuntime(18719): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(18719):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime(18719):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(18719):        at com.evilratt.flutter_zoom_sdk.FlutterZoomSdkPlugin$4.onZoomSDKLoginResult(FlutterZoomSdkPlugin.java:302)
E/AndroidRuntime(18719):        at us.zoom.sdk.ZoomSDK.onSDKLoginReturn(ZoomSDK.java:7)
E/AndroidRuntime(18719):        at us.zoom.sdk.ZoomSDK$b.onPTAppEvent(ZoomSDK.java:2)
E/AndroidRuntime(18719):        at com.zipow.videobox.ptapp.PTUI.dispatchPTAppEventImpl(PTUI.java:161)
E/AndroidRuntime(18719):        at com.zipow.videobox.ptapp.PTUI.dispatchPTAppEvent(PTUI.java:1)
E/AndroidRuntime(18719):        at com.zipow.videobox.mainboard.Mainboard.heartBeat4SingleProcessImpl(Native Method)
E/AndroidRuntime(18719):        at com.zipow.videobox.mainboard.Mainboard.heartBeatForSDK(Mainboard.java:1)
E/AndroidRuntime(18719):        at com.zipow.videobox.ptapp.PTApp.dispatchIdleMessage(PTApp.java:5)
E/AndroidRuntime(18719):        at com.zipow.videobox.VideoBoxApplication$d.run(VideoBoxApplication.java:7)
E/AndroidRuntime(18719):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(18719):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18719):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18719):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18719):        at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(18719):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18719):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18719):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (18719): Sending signal. PID: 18719 SIG: 9

**Comment by evilrat** [comment] 2021-12-14 12:54
Looking into it

**Comment by Ghoral** [comment] 2021-12-26 06:04
hello @evilrat,
There was supposed to be a new release yesterday. Is there any next date for release?

**Comment by Ghoral** [comment] 2022-01-12 07:08
Hello @evilrat any update on the next release.

**Comment by Ghoral** [comment] 2022-01-13 06:50
Thank You evilrat, for update on ios..since lockdown are happening and online classes are must.this was really important in our app.

**Comment by Ghoral** [comment] 2022-01-15 07:25
Hello @evilrat,
On ios when the login credentials are sent on startMeetingNormal it freezes the screen (invalid and valid in both cases) I tried to get an error log but nothing is returned. startMeetingNormal works perfectly but it takes a lot of attempts to start the meeting.

**Comment by Ghoral** [comment] 2022-01-15 08:01
@evilrat  seems the problem is not with startzoomNormal.

Zomm is not inizialized at first.

`The following PlatformException was thrown while activating platform stream on channel
com.evilratt/zoom_sdk_event_stream:
PlatformException(Zoom SDK error, ZoomSDK is not initialized, null, null)

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:506:9)
<asynchronous suspension>`

**Comment by evilrat** [comment] 2022-01-15 11:30
> @evilrat seems the problem is not with startzoomNormal.
> 
> Zomm is not inizialized at first.
> 
> `The following PlatformException was thrown while activating platform stream on channel com.evilratt/zoom_sdk_event_stream: PlatformException(Zoom SDK error, ZoomSDK is not initialized, null, null)
> 
> When the exception was thrown, this was the stack: #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7) #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18) #2 EventChannel.receiveBroadcastStream. (package:flutter/src/services/platform_channel.dart:506:9) `

can you proivide example code you are executing for ios

**Comment by Ghoral** [comment] 2022-01-15 12:02
@evilrat here is my code.
initZoom is inside of initState..

![code](https://user-images.githubusercontent.com/49188349/149621004-ac068fcf-9fb9-488f-98d1-8e7182261a73.png)

user credentials come from a text field form.
![code1](https://user-images.githubusercontent.com/49188349/149621022-813eb691-b7a8-4c20-8f08-62aeb3a0c13d.png)


on android Its working perfectly. but in ios I need to go back and come to this screen in order to startTheMeeting.

**Comment by Ghoral** [comment] 2022-01-15 12:47
@evilrat tried code from pub.dev aloso.
Here is the sequence

1. first click
- initialize zoom
logs:
No old cache folder exist
flutter: init zoom response -> [0, 0]
error was 0
error was 22 
 --meeting doesnot starts

2. second click
flutter: init zoom ->[0, 0]
Got response from start: MobileRTCMeetError
flutter: zoom successs
   --meeting starts successful.

**Comment by Ghoral** [comment] 2022-01-15 12:49
` startZoomClass( classInfo) async {
    try {
      zoom
          .initZoom(
        ZoomOptions(
          domain: "zoom.us",
          appKey: 'yP1cPXwSbaRpek0OarTQuDoDfjLbBokrykUV',
          appSecret: 'LxSp7fOLaS1N7yHQrxaW8meLf9u0XFc6Fmbr',
        ),
      )
          .then((value) async {
    
        zoom
            .startMeetingNormal(
              ZoomMeetingOptions(
                userId: 'myemail',
                meetingId: 'meetingId',
                userPassword: 'password',
                disableDialIn: "true",
                disableDrive: "true",
                disableInvite: "false",
                disableShare: "false",
                noAudio: "false",
                disableTitlebar: "false",
                viewOptions: "false",
                noDisconnectAudio: "false",
              ),
            )
            .then((value) => print('zoom successs'))
            .catchError((er) {
        
        });
      }).catchError((err) {
      
      });
    } catch (e) {
      Navigator.of(context).pop();
    }
  }`

**Comment by Ghoral** [comment] 2022-01-15 12:51
here is the second way
![code1](https://user-images.githubusercontent.com/49188349/149622327-21d6b54f-48f3-427f-a8c1-c761328f22c9.png)

**Comment by Ghoral** [comment] 2022-01-15 12:54
The only issue is it starts meeting in second attempt (https://github.com/evilrat/flutter_zoom_sdk/issues/33#issuecomment-1013676502)
.. else everything works.

**Comment by Ghoral** [comment] 2022-01-16 05:24
Hello @evilrat,
Tested it on android and everything works great. The issue is only on ios.
Thank you.

**Comment by evilrat** [comment] 2022-01-17 08:09
> Hello @evilrat, Tested it on android and everything works great. The issue is only on ios. Thank you.

working on it.....give us some time to fix it

**Comment by Ghoral** [comment] 2022-01-17 08:17
@evilrat  sure.

**Comment by Ghoral** [comment] 2022-02-03 13:36
Hello @evilrat,

Is there any update on this issue?.

**Comment by evilrat** [comment] 2022-02-04 04:34
> Hello @evilrat,
> 
> Is there any update on this issue?.

still not resolved

**Comment by Ghoral** [comment] 2022-03-22 11:25
Hello @evilrat this issue still persists. Has it been fixed

**Comment by evilrat** [comment] 2022-03-22 13:02
> Hello @evilrat this issue still persists. Has it been fixed

no....looking into it

**Comment by evilrat** [comment] 2022-03-22 13:03
> Hello @evilrat this issue still persists. Has it been fixed

can you elaborate the issue......after success login or after failed first login....due to some issue

**Comment by Ghoral** [comment] 2022-03-22 13:07
it is happening after failed first login.

steps:
- Enter incorrect email
   - no app crash
- Again enter correct email
  - app crashes

**Comment by ark-brighthustle** [comment] 2022-03-29 10:31
> it is happening after failed first login.
> 
> steps:
> 
> * Enter incorrect email
>   
>   * no app crash
> * Again enter correct email
>   
>   * app crashes

Patch has bee released........please verify and close the issue.......as of now the issue is fixed

**Closed** 2022-03-29 19:19 UTC
Labels: issue-type: bug, severrity: high, issue-type: bug resolved, issue-platform: android
